import fs from'node:fs';
const b=fs.readFileSync(process.argv[2]||'SuperAgent_V11_5_FULL.js','utf8'),o=fs.readFileSync(process.argv[3]||'SuperAgent_V11_5_1_FULL.js','utf8');
const names=s=>[...s.matchAll(/(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/g)].map(x=>x[1]);
const tables=s=>[...s.matchAll(/CREATE TABLE IF NOT EXISTS\s+([A-Za-z0-9_]+)/gi)].map(x=>x[1]);
const bf=names(b),of=names(o),bt=tables(b),ot=tables(o),set=x=>new Set(x),count=(s,p)=>(s.match(p)||[]).length;
const mf=[...set(bf)].filter(x=>!set(of).has(x)),mt=[...set(bt)].filter(x=>!set(ot).has(x));
const chain=o.match(/const MODEL_CHAIN=\[([\s\S]*?)\n\];\nconst PRIMARY_MODEL/);if(!chain)throw Error('MODEL_CHAIN missing');
const ids=[...chain[1].matchAll(/id:"([^"]+)"/g)].map(x=>x[1]),timeouts=[...chain[1].matchAll(/timeoutMs:(\d+)/g)].map(x=>Number(x[1]));
const exp=['gemini::gemini-3.5-flash-lite','gemini::gemini-3.1-flash-lite','gemini::gemini-3-flash-preview'];
const checks={
version:o.includes('const V10_VERSION="11.5.1";')&&o.includes("const V115_SCHEMA_VERSION='11.5.1';"),models:JSON.stringify(ids)===JSON.stringify(exp),googleOnly:ids.every(x=>x.startsWith('gemini::')),litePriority:ids[0].includes('flash-lite')&&ids[1].includes('flash-lite'),strongThird:ids[2]==='gemini::gemini-3-flash-preview',noLatestLiteAlias:!o.includes('gemini::gemini-flash-lite-latest'),noBroken25:!o.includes('gemini::gemini-2.5-flash-lite'),routerRemoved:o.includes('v11_semantic_router:false'),budget:o.includes('const TOTAL_AI_BUDGET_MS=10000;')&&timeouts.reduce((a,c)=>a+c,0)<=10000,functionsRetained:mf.length===0&&set(bf).size===set(of).size,tablesRetained:mt.length===0&&set(bt).size===set(ot).size,noNewFunctionDeclarations:bf.length===of.length,noQuerySecrets:!o.includes('searchParams.get("key")')&&!o.includes("searchParams.get('key')"),headerAuth:o.includes('X-SuperAgent-Key')&&o.includes('Authorization'),queueHeartbeat:o.includes('V115_QUEUE_HEARTBEAT_MS=8000')&&o.includes('renewInboxLeaseV115'),mutationDisarm:o.includes('finally{if(!ok)v113DisarmMutationReceipt(chatId);}')&&o.includes('if(should&&!handled)v113DisarmMutationReceipt(chatId);'),voiceDeadline:o.includes('V115_VOICE_TOTAL_BUDGET_MS=20000')&&o.includes('V115_VOICE_STT_TIMEOUT_MS=11000'),telegramTimeout:o.includes('V113_TELEGRAM_TIMEOUT_MS')&&o.includes('telegramApiWithRetry'),continuationTimeout:o.includes('V115_CONTINUATION_TIMEOUT_MS=1800'),currentGate:o.includes('مين رئيس مصر؟')&&o.includes('سعر الدولار؟')&&o.includes('مين CEO جوجل؟'),personalGate:o.includes('needsPersonalizationContextV115'),purge:o.includes('purgeTransportForChatV115'),worldUpdates:o.includes("if(!mutating.has(action)&&Array.isArray(intent?.world_updates)"),schemaFast:o.includes('ensureRuntimeSchemaReadyV115'),briefWindows:o.includes("clockInWindowV115(now.time,'08:00','08:09')")&&o.includes("clockInWindowV115(now.time,'21:00','21:09')"),holidaySafe:o.includes('if(!successful){const stale=await cacheGetAnyV113'),directHandlerOnce:count(o,/if\(await handleDirectCommands\(env,chatId,text\)\)return;/g)===1,failureIncident:o.includes('v115_direct_chat_all_models_failed'),accurateTimeout:o.includes('Timeout بعد ${attemptMs}ms'),noEvalRegression:count(o,/\beval\s*\(/g)===count(b,/\beval\s*\(/g)&&count(o,/new\s+Function\s*\(/g)===count(b,/new\s+Function\s*\(/g)};
const failed=Object.entries(checks).filter(([,v])=>!v).map(([k])=>k);if(failed.length)throw Error(JSON.stringify({failed,ids,timeouts,mf,mt},null,2));
const cert=JSON.parse(fs.readFileSync('V11_5_1_CERTIFICATION.json','utf8'));Object.assign(cert,{base_functions:set(bf).size,retained_functions:set(of).size,base_tables:set(bt).size,retained_tables:set(ot).size,model_timeouts:timeouts,checks,failed_checks:failed});fs.writeFileSync('V11_5_1_CERTIFICATION.json',JSON.stringify(cert,null,2));console.log(JSON.stringify({ok:true,functions:set(of).size,tables:set(ot).size,ids,timeouts,checks}));
