from pathlib import Path
p=Path('SuperAgent_V10_2_Semantic_Stability.js'); s=p.read_text()
def rep(a,b,n=1):
 global s
 if a not in s: raise SystemExit('missing:'+a[:80])
 s=s.replace(a,b,n)
rep('const V10_VERSION="10.2";const V10_NAME="Super Agent V10 — Life OS · Semantic Stability";','const V10_VERSION="10.3";const V10_NAME="Super Agent V10 — Life OS · Reliability Lock";const RELIABILITY_RECEIPT_TTL_MINUTES=10;const RUNTIME_FAILURE_RETENTION_DAYS=30;')
rep('dependency_repair:true,duration_conflicts:true','dependency_repair:true,reliability_lock:true,operation_receipts:true,runtime_failure_log:true,health_db_probe:true,duration_conflicts:true')
rep('if(request.method==="GET"&&url.pathname==="/health"){\nreturn json({ok:true,version:V10_VERSION,now:cairoNow(),db:!!env.DB,omniai_service:!!env.OMNIAI_SERVICE,life_os:true,voice:!!((env.OMNIAI_SERVICE&&env.OMNIAI_API_KEY)||env.GROQ_API_KEY||env.VOICE_TRANSCRIBE_URL)});\n}','if(request.method==="GET"&&url.pathname==="/health")return reliabilityHealth(env);')
rep('message:"Super Agent V10.2 Semantic Stability is ready"','message:"Super Agent V10.3 Reliability Lock is ready"')
rep('dependency_repair:true,universal_recurrence:true','dependency_repair:true,reliability_lock:true,operation_receipts:true,runtime_failure_log:true,health_db_probe:true,universal_recurrence:true')
needle='await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_telegram_updates_started ON telegram_updates(started_at)`).run();\n'
rep(needle,needle+'''await env.DB.prepare(`CREATE TABLE IF NOT EXISTS runtime_failures (\nid INTEGER PRIMARY KEY AUTOINCREMENT,\nincident_id TEXT NOT NULL UNIQUE,\nchat_id TEXT,\nscope TEXT NOT NULL,\nerror_text TEXT NOT NULL,\ncontext_json TEXT NOT NULL DEFAULT '{}',\ncreated_at TEXT NOT NULL\n)`).run();\nawait env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_runtime_failures_created ON runtime_failures(created_at)`).run();\nawait env.DB.prepare(`CREATE TABLE IF NOT EXISTS operation_receipts (\nid INTEGER PRIMARY KEY AUTOINCREMENT,\nchat_id TEXT NOT NULL,\nfingerprint TEXT NOT NULL,\naction TEXT NOT NULL,\nstate TEXT NOT NULL DEFAULT 'committed',\nresponse_text TEXT,\ncreated_at TEXT NOT NULL,\nupdated_at TEXT NOT NULL\n)`).run();\nawait env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_operation_receipts_lookup ON operation_receipts(chat_id,fingerprint,created_at)`).run();\n''')
helper=r'''function reliabilityFingerprint(value){const str=normalizeArabicLoose(String(value||"")).replace(/\s+/g," ").trim();let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return `fnv1a:${(h>>>0).toString(16).padStart(8,"0")}:${str.length}`;}
function newIncidentId(){return `SA-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;}
async function recordRuntimeFailure(env,{chatId=null,scope="runtime",error,context={}}={}){const incidentId=newIncidentId();const err=safeError(error||"Unknown failure");console.error(`[${incidentId}] ${scope}: ${err}`);try{if(env?.DB)await env.DB.prepare(`INSERT INTO runtime_failures(incident_id,chat_id,scope,error_text,context_json,created_at) VALUES (?,?,?,?,?,?)`).bind(incidentId,chatId?String(chatId):null,String(scope),String(err).slice(0,1200),JSON.stringify(context||{}).slice(0,4000),new Date().toISOString()).run();}catch(e){console.error("runtime failure log failed",safeError(e));}return incidentId;}
async function persistWorldUpdatesSafely(env,chatId,intent){try{await persistWorldUpdatesFromIntent(env,chatId,intent);}catch(e){await recordRuntimeFailure(env,{chatId,scope:"world_model_noncritical",error:e,context:{action:intent?.action}});}}
async function getRecentOperationReceipt(env,chatId,fingerprint){const cutoff=new Date(Date.now()-RELIABILITY_RECEIPT_TTL_MINUTES*60000).toISOString();return env.DB.prepare(`SELECT * FROM operation_receipts WHERE chat_id=? AND fingerprint=? AND state='committed' AND created_at>=? ORDER BY id DESC LIMIT 1`).bind(String(chatId),String(fingerprint),cutoff).first();}
async function saveOperationReceipt(env,chatId,fingerprint,action,responseText){const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO operation_receipts(chat_id,fingerprint,action,state,response_text,created_at,updated_at) VALUES (?,?,?,?,?,?,?)`).bind(String(chatId),String(fingerprint),String(action),"committed",String(responseText||"").slice(0,12000),now,now).run();}
async function cleanupReliabilityData(env){try{const cutoff=new Date(Date.now()-RUNTIME_FAILURE_RETENTION_DAYS*86400000).toISOString();const receipts=new Date(Date.now()-86400000).toISOString();await env.DB.batch([env.DB.prepare(`DELETE FROM runtime_failures WHERE created_at<?`).bind(cutoff),env.DB.prepare(`DELETE FROM operation_receipts WHERE created_at<?`).bind(receipts)]);}catch(e){console.warn("Reliability cleanup failed",safeError(e));}}
async function reliabilityHealth(env){const base={ok:true,version:V10_VERSION,now:cairoNow(),db:false,omniai_service:!!env.OMNIAI_SERVICE,life_os:true,reliability_lock:true,voice:!!((env.OMNIAI_SERVICE&&env.OMNIAI_API_KEY)||env.GROQ_API_KEY||env.VOICE_TRANSCRIBE_URL)};if(!env.DB)return json({...base,ok:false,error:"DB binding missing"},503);try{await ensureSchemaOnce(env);const probe=await env.DB.prepare(`SELECT 1 AS ok`).first();const since=new Date(Date.now()-3600000).toISOString();const f=await env.DB.prepare(`SELECT COUNT(*) AS c FROM runtime_failures WHERE created_at>=?`).bind(since).first();return json({...base,db:Number(probe?.ok||0)===1,recent_failures_1h:Number(f?.c||0)});}catch(e){const incident=await recordRuntimeFailure(env,{scope:"health_db_probe",error:e});return json({...base,ok:false,error:"DB probe failed",incident_id:incident},503);}}

'''
rep('async function claimTelegramUpdate(env,update){',helper+'async function claimTelegramUpdate(env,update){')
rep('console.error("Telegram update error:",error);\ntry{\nconst msg=`⚠️ حصل خطأ: ${safeError(error)}`;','const incidentId=await recordRuntimeFailure(env,{chatId,scope:"telegram_update",error,context:{update_id:claim.key}});\ntry{\nconst msg=`⚠️ العملية ما اكتملتش، ومش هاعتبرها ناجحة. رقم التتبع: ${incidentId}`;')
rep('async function executeIntent(env,chatId,intent,options={}){\nawait persistWorldUpdatesFromIntent(env,chatId,intent);','async function executeIntent(env,chatId,intent,options={}){\nawait persistWorldUpdatesSafely(env,chatId,intent);')
rep('if(intent.action==="create"){\n','if(intent.action==="create"){\nconst receiptFingerprint=reliabilityFingerprint(intent._base_text||JSON.stringify({action:intent.action,items:intent.items,recurring_items:intent.recurring_items,dependencies:intent.dependencies}));\nconst priorReceipt=await getRecentOperationReceipt(env,chatId,receiptFingerprint);\nif(priorReceipt?.response_text){await sendText(env,chatId,String(priorReceipt.response_text),quickMenuKeyboard());return;}\n')
rep('async function executeIntent(env,chatId,intent,options={}){','''async function rollbackCreatedScheduleBatch(env,chatId,one,rules){const rollback=[];for(const x of one||[])if(Number(x.id)){rollback.push(env.DB.prepare(`DELETE FROM event_dependencies WHERE chat_id=? AND ((source_type='reminder' AND source_id=?) OR (target_type='reminder' AND target_id=?))`).bind(chatId,Number(x.id),Number(x.id)));rollback.push(env.DB.prepare(`DELETE FROM reminders WHERE id=? AND chat_id=?`).bind(Number(x.id),chatId));}for(const x of rules||[])if(Number(x.id))rollback.push(env.DB.prepare(`DELETE FROM schedule_rules WHERE id=? AND chat_id=?`).bind(Number(x.id),chatId));if(rollback.length)await env.DB.batch(rollback);}\n\nasync function executeIntent(env,chatId,intent,options={}){''')
old='''}catch(e){\nconst rollback=[];\nfor(const x of one)if(Number(x.id)){rollback.push(env.DB.prepare(`DELETE FROM event_dependencies WHERE chat_id=? AND ((source_type='reminder' AND source_id=?) OR (target_type='reminder' AND target_id=?))`).bind(chatId,Number(x.id),Number(x.id)));rollback.push(env.DB.prepare(`DELETE FROM reminders WHERE id=? AND chat_id=?`).bind(Number(x.id),chatId));}\nfor(const x of rules)if(Number(x.id))rollback.push(env.DB.prepare(`DELETE FROM schedule_rules WHERE id=? AND chat_id=?`).bind(Number(x.id),chatId));\nif(rollback.length)await env.DB.batch(rollback);\nthrow e;\n}\nawait writeAudit(env,chatId,{action:"create",entityType:"schedule_batch",entityId:"batch",summary:`إنشاء ${one.length+rules.length} موعد/تكرار`,after:{one,rules},undo:{type:"delete_created_schedule",reminder_ids:one.map(x=>Number(x.id)).filter(Boolean),rule_ids:rules.map(x=>Number(x.id)).filter(Boolean)}});'''
new='''}catch(e){await rollbackCreatedScheduleBatch(env,chatId,one,rules);throw e;}\ntry{await writeAudit(env,chatId,{action:"create",entityType:"schedule_batch",entityId:"batch",summary:`إنشاء ${one.length+rules.length} موعد/تكرار`,after:{one,rules},undo:{type:"delete_created_schedule",reminder_ids:one.map(x=>Number(x.id)).filter(Boolean),rule_ids:rules.map(x=>Number(x.id)).filter(Boolean)},strict:true});}catch(e){await rollbackCreatedScheduleBatch(env,chatId,one,rules);throw new Error(`Audit commit failed; operation rolled back: ${safeError(e)}`);}'''
rep(old,new)
rep('const answer=`✅ تم الحفظ:\n\n${lines.join("\\n")}${modelFooter(env,chatId,intent)}`;\n\nawait sendText(env,chatId,answer,quickMenuKeyboard());','const answer=`✅ تم الحفظ:\n\n${lines.join("\\n")}${modelFooter(env,chatId,intent)}`;\n\nawait saveOperationReceipt(env,chatId,receiptFingerprint,"create",answer);\nawait sendText(env,chatId,answer,quickMenuKeyboard());')
rep('async function writeAudit(env,chatId,{action,entityType,entityId=null,summary,before={},after={},undo={}}){','async function writeAudit(env,chatId,{action,entityType,entityId=null,summary,before={},after={},undo={},strict=false}){')
rep('}catch(e){console.warn("Audit write failed",safeError(e));}\n}','}catch(e){console.warn("Audit write failed",safeError(e));if(strict)throw e;}\n}')
rep('async scheduled(controller,env,ctx){\nctx.waitUntil(Promise.all([deliverDueReminders(env,controller?.scheduledTime),runV10PeriodicIntelligence(env,controller?.scheduledTime)]));\n}','async scheduled(controller,env,ctx){\nctx.waitUntil(Promise.allSettled([deliverDueReminders(env,controller?.scheduledTime),runV10PeriodicIntelligence(env,controller?.scheduledTime),cleanupReliabilityData(env)]).then(async results=>{for(let i=0;i<results.length;i++)if(results[i].status==="rejected")await recordRuntimeFailure(env,{scope:`scheduled_${i}`,error:results[i].reason});}));\n}')
rep('  const passed=tests.filter(x=>x.ok).length;return{ok:passed===tests.length,passed,total:tests.length,tests};','  add("reliability fingerprint stable",reliabilityFingerprint(" فكرني بكرة 5 ")===reliabilityFingerprint("فكرني بكرة 5"));\n  add("reliability fingerprint changes",reliabilityFingerprint("A")!==reliabilityFingerprint("B"));\n  add("incident id format",/^SA-[A-Z0-9]+-[A-Z0-9]{5}$/.test(newIncidentId()));\n  const passed=tests.filter(x=>x.ok).length;return{ok:passed===tests.length,passed,total:tests.length,tests};')
out=Path('SuperAgent_V10_3_Reliability_Lock.js');out.write_text(s)
import hashlib
b=out.read_bytes();assert len(b)==306117,(len(b));assert hashlib.sha256(b).hexdigest()=='938abf9d88a40cf1d1b4ac1d14d6422fc476b3673d4123d6c2a38509f296d118'
print('built',len(b))
