import{execFileSync}from'node:child_process';import fs from'node:fs';
const U=process.env.URL,D=process.env.DB,C=String(process.env.STAGING_ADMIN_CHAT_ID||''),S=process.env.WEBHOOK_SECRET,cfg=process.env.WRANGLER_CONFIG||'wrangler.v1151.jsonc',sleep=m=>new Promise(r=>setTimeout(r,m)),esc=s=>String(s).replaceAll("'","''");
if(!U||!D||!C||!S)throw Error('live env missing');
function q(sql){return JSON.parse(execFileSync('npx',['wrangler','d1','execute',D,'--remote','--config',cfg,'--command',sql,'--json'],{encoding:'utf8'}))?.[0]?.results||[]}
let seq=2100000000+(Date.now()%5000000),mid=500000,started=new Date().toISOString(),passes=[];
async function post(text,id=++seq){const b={update_id:id,message:{message_id:++mid,date:Math.floor(Date.now()/1000),chat:{id:Number(C),type:'private'},from:{id:Number(C),is_bot:false,first_name:'V1151'},text}},t=Date.now(),r=await fetch(U+'/telegram',{method:'POST',headers:{'content-type':'application/json','X-Telegram-Bot-Api-Secret-Token':S},body:JSON.stringify(b)});if(!r.ok)throw Error('webhook '+r.status);return{id,t}}
async function wait(id,max=70000){let row,end=Date.now()+max;while(Date.now()<end){row=q(`SELECT status,attempts,last_error FROM telegram_inbox_v106 WHERE update_id='${id}' LIMIT 1`)[0];if(row?.status==='done')return row;if(row?.status==='failed')throw Error('failed '+id+' '+row.last_error);await sleep(400)}throw Error('timeout '+id+' '+JSON.stringify(row))}
function ok(name,c,d=''){if(!c)throw Error('FAIL '+name+' '+d);passes.push({name,detail:String(d)});console.log('PASS',name,d)}
q(`DELETE FROM shopping_sessions WHERE chat_id='${esc(C)}';DELETE FROM smart_list_items WHERE chat_id='${esc(C)}';DELETE FROM smart_lists WHERE chat_id='${esc(C)}';DELETE FROM reminders WHERE chat_id='${esc(C)}' AND title LIKE '%V1151LIVE%';`);
let x=await post('انت اسمك اي'),r=await wait(x.id);ok('identity',r.attempts===1,Date.now()-x.t+'ms');
x=await post('عامل اي');r=await wait(x.id);ok('egyptian casual',r.attempts===1,Date.now()-x.t+'ms');
x=await post('سعر الدولار؟');r=await wait(x.id);let last=q(`SELECT content FROM conversation_messages WHERE chat_id='${esc(C)}' AND role='assistant' ORDER BY id DESC LIMIT 1`)[0]?.content||'';ok('current-data no stale guess',/مصدر|مش هخمن|لحظية/.test(last),last.slice(0,140));
const list='بص عاوز اشتري\nعيش تورتيلا\nعيش توست\nفينو اسود\nفصوص رومي\nشيدر طبيعي\nكاجو\nفستق\nكوفي شيك\nحليب دينا\nايس كريم دينا\nوبطاطس طبيعية';x=await post(list);r=await wait(x.id);let rows=q(`SELECT title FROM smart_list_items WHERE chat_id='${esc(C)}' AND status='pending'`);ok('shopping 11/11',rows.length===11,'items='+rows.length);
x=await post('فكرني يوم 3 نوفمبر 2026 الساعة 7:23 مساء أراجع V1151LIVE-SINGLE');r=await wait(x.id);rows=q(`SELECT local_date,local_time FROM reminders WHERE chat_id='${esc(C)}' AND title LIKE '%V1151LIVE-SINGLE%' AND cancelled=0`);ok('reminder exact',rows.length===1&&rows[0].local_date==='2026-11-03'&&rows[0].local_time==='19:23',JSON.stringify(rows));
const dup=++seq;await Promise.all([post('فكرني يوم 4 نوفمبر 2026 الساعة 7:25 مساء أراجع V1151LIVE-IDEMP',dup),post('فكرني يوم 4 نوفمبر 2026 الساعة 7:25 مساء أراجع V1151LIVE-IDEMP',dup)]);r=await wait(dup);rows=q(`SELECT id FROM reminders WHERE chat_id='${esc(C)}' AND title LIKE '%V1151LIVE-IDEMP%' AND cancelled=0`);ok('duplicate exactly once',rows.length===1,'rows='+rows.length+' attempts='+r.attempts);
const a=await post('/shopping'),b=await post('/today'),c=await post('صباح الفل');const rr=await Promise.all([wait(a.id),wait(b.id),wait(c.id)]);ok('same-chat burst',rr.every(z=>z.attempts===1),JSON.stringify(rr.map(z=>z.attempts)));
const failures=q(`SELECT scope,error,created_at FROM runtime_failures WHERE created_at>='${started}'`);ok('runtime failures zero',failures.length===0,JSON.stringify(failures));
fs.writeFileSync('V11_5_1_LIVE_REPORT.json',JSON.stringify({ok:true,version:'11.5.1',sha256:process.env.V1151_SHA,started,finished:new Date().toISOString(),passes,runtime_failures:failures},null,2));
