import fs from 'node:fs';
const p='tools/build_v11.mjs';
let b=fs.readFileSync(p,'utf8');
const lines=b.split('\n');
const identity=lines.findIndex(x=>x.includes("'identity insertion'"));
if(identity<0)throw new Error('identity insertion builder line not found');
lines[identity]="{const m=s.indexOf('// V10.7: normal human language is interpreted semantically first.');if(m<0)throw new Error('V11 identity marker missing');s=s.slice(0,m)+'if(await handleV11Identity(text,env,chatId))return;\\n'+s.slice(m);}";
const router=lines.findIndex(x=>x.includes("'router insertion'"));
if(router<0)throw new Error('router insertion builder line not found');
lines[router]="{const p=s.indexOf('parseIntentWithFallback');if(p<0)throw new Error('parseIntentWithFallback missing');console.log('V11_PARSE_SNIPPET_START\\n'+s.slice(Math.max(0,p-800),p+9000)+'\\nV11_PARSE_SNIPPET_END');}";
fs.writeFileSync(p,lines.join('\n'));
console.log('patched V11 builder for parse anchor discovery');
